-- 코드를 작성해주세요
SELECT COUNT(*) 'COUNT'
FROM ECOLI_DATA 
WHERE CONV(GENOTYPE, 10, 2) LIKE '%101' || CONV(GENOTYPE, 10, 2) LIKE '%001' || CONV(GENOTYPE, 10, 2) LIKE '%100' || CONV(GENOTYPE, 10, 2) LIKE '1';

# SELECT COUNT
# FROM ECOLI_DATA
# WHERE (GENOTYPE & 8) = 0 AND 