-- 코드를 작성해주세요
# SELECT ED1.ID, COUNT(ED2.ID) CHILD_COUNT
# FROM ECOLI_DATA ED1 LEFT JOIN ECOLI_DATA ED2 ON ED1.ID = ED2.PARENT_ID
# GROUP BY ED1.ID
# ORDER BY ID ASC;

SELECT E1.ID, COUNT(E2.PARENT_ID) AS CHILD_COUNT
FROM ECOLI_DATA E1
LEFT JOIN ECOLI_DATA E2 ON E1.ID = E2.PARENT_ID
GROUP BY E1.ID
ORDER BY E1.ID;
