-- 코드를 입력하세요
SELECT PR.PRODUCT_CODE, (SUM(OS.SALES_AMOUNT) * PR.PRICE) SALES 
FROM PRODUCT PR JOIN OFFLINE_SALE OS ON PR.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY PR.PRODUCT_CODE 
ORDER BY SALES DESC, PRODUCT_CODE ASC;