-- 코드를 작성해주세요
SELECT  ID,
CASE
WHEN COLONY_RANK <= 0.25 THEN 'CRITICAL'
WHEN COLONY_RANK <= 0.5 THEN 'HIGH'
WHEN COLONY_RANK <= 0.75 THEN 'MEDIUM'
ELSE 'LOW'
END AS COLONY_NAME
FROM (SELECT ID,  SIZE_OF_COLONY, PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS COLONY_RANK FROM ECOLI_DATA) RANKED
ORDER BY ID ASC;