-- 코드를 입력하세요
SELECT UGU.USER_ID, UGU.NICKNAME, CONCAT_WS(' ', UGU.CITY, UGU.STREET_ADDRESS1, UGU.STREET_ADDRESS2) 전체주소, CONCAT(SUBSTR(UGU.TLNO, 1, 3), '-', SUBSTR(UGU.TLNO, 4, 4), '-', SUBSTR(UGU.TLNO, 8, 4)) 전화번호
FROM USED_GOODS_USER UGU JOIN USED_GOODS_BOARD UGB ON UGU.USER_ID = UGB.WRITER_ID
GROUP BY UGB.WRITER_ID
HAVING COUNT(UGB.BOARD_ID) >= 3
ORDER BY UGU.USER_ID DESC;