# SELECT ID,
# CASE
# WHEN SIZE_OF_COLONY <= 100 THEN 'LOW'
# WHEN 100 < SIZE_OF_COLONY AND SIZE_OF_COLONY <=1000 THEN 'MEDIUM'
# WHEN 1000 < SIZE_OF_COLONY THEN 'HIGH'
# END AS SIZE
# FROM ECOLI_DATA
# ORDER BY ID ASC;

# 100 < SIZE_OF_COLONY <= 1000 이러면 안됨 / WHEN 100 < SIZE_OF_COLONY AND SIZE_OF_COLONY <=1000 THEN 'MEDIUM' 이렇게 해야함.

SELECT ID, 
CASE
WHEN SIZE_OF_COLONY <= 100 THEN 'LOW'
WHEN SIZE_OF_COLONY > 100 AND SIZE_OF_COLONY <= 1000 THEN 'MEDIUM'
WHEN SIZE_OF_COLONY > 1000 THEN 'HIGH'
END AS SIZE
FROM ECOLI_DATA
ORDER BY ID ASC;
