-- 코드를 입력하세요
SELECT CH.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CH JOIN CAR_RENTAL_COMPANY_CAR CC ON CH.CAR_ID = CC.CAR_ID
WHERE CC.CAR_TYPE = '세단' AND CH.START_DATE LIKE '_____10%'
GROUP BY CH.CAR_ID
ORDER BY CC.CAR_ID DESC;