-- 코드를 입력하세요
SELECT BO.BOOK_ID, AU.AUTHOR_NAME, DATE_FORMAT(BO.PUBLISHED_DATE, '%Y-%m-%d') FROM BOOK BO, AUTHOR AU WHERE BO.AUTHOR_ID = AU.AUTHOR_ID AND BO.CATEGORY = '경제' ORDER BY PUBLISHED_DATE ASC;